### PR TITLE
add secrets detector action

### LINKED ISSUE #50: Add detect-secrets audit GitHub Actions
https://github.com/Yelp/detect-secrets

### PR DESCRIPTION
**Pull request by gnomex**
Fixes #50

### CODE REVIEW

**Comment by bianchidotdev** [comment]
Hey there. Thanks for the contribution! Looks like that action by `evanextreme` doesn't support using a baseline which is what I'm aiming at here (see `.secrets.baseline` at the root of the repo.

**Comment by gnomex** [comment]
Oops, got it. Refactoring asap

**Comment by gnomex** [comment]
There is a [fork](https://github.com/RobertFischer/detect-secrets-action) of the action that support the `.baseline` file. If still doesn't fit I will create a new one

**Review by bianchidotdev — APPROVED** [review]
Thanks! This looks great! I appreciate the help

**Pull request merged**
